[package]
name = "funpar-t2-22-project-ligmaboys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
check = "1.0.0"
fmt = "0.1.0"
